### ISSUE TITLE
eman2 boxer coordinates are wrong when picking dm3

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1421]
This is a very old EMAN issue: dm3 images are flipped horizontally when displayed in EMAN. So the coordinates that are saved after e2boxer protocol become wrong as soon as dm3 is converted to mrc.
I would suggest to fix this by modifying Y-coordinate (Ynew=micSize-Yold) when saving output from e2boxer protocol.

**Comment by pconesa** [comment]
Thanks, @azazellochg, I think is the same with tif files....have you got a dm3 file we can make a quick test?

**Comment by azazellochg** [comment]
I think you are right about tif as well. Here is a dm3 example file.
[image.dm3.zip](https://github.com/I2PC/scipion/files/1620035/fixed-fr8-undil-img5.dm3.zip)

**Comment by pconesa** [comment]
thanks @azazellochg , I've fixed this, which took me almost the same time than "adding that warning about being a tif file" in the validation...so I'm wondering if we are missing anything here. @delarosatrevin , @josuegbl ?

**Comment by josuegbl** [comment]
I'm not agree with fix this, and I prefer a warning in the validation. I think that the user should be aware, but scipion should not modify the original data, because we would be creating an inconsistency breaking  the bookkeeping, one of the scipion's strengths. @cossorzano gave us an idea: create a protocol that invert the coordinates. I think this new protocol is a better solution due to the user is aware that is doing a flip to the coordinates and generates a NEW setOfCoordinates.

**Comment by pconesa** [comment]
Sorry @azazellochg , as you can see, there is a strong disagreement here. @josuegbl, I've got a question ....do we "literally" store other outputs in all cases. Things like shifts, angles,.....are we always in all cases keeping the original data? In any case, this is something you cannot easily explain to a user. I agree with keeping the warning due to the fact that the visualization is shifted between Scipion and Eman, but knowing that, I don't see why we should not compensate that shift if that makes the user experience clearly cleaner and smooth.

**Comment by azazellochg** [comment]
Hi @josuegbl @pconesa , I have looked more into this issue. I found that since EMAN2.1 (we use 2.12 in Scipion) the orientation display issue was fixed and now the tif/dm3 micrographs look the same way as they look in Digital micrograph (I have just checked on one of our microscopes). So it appears that ImageHandler is flipping dm3/tiffs then upon convertion to mrc (particle extraction) and original coordinates are correct?
PS. The original reason (before EMAN2.1) for flipping in EMAN was: "Internally, the EMAN2 convention is that the origin is at the lower left corner of the display. When we read files that use the opposite convention (origin upper left), the data is vertically flipped on read (and write), so they should be displayed and processed correctly within EMAN2"

**Comment by azazellochg** [comment]
Hi @pconesa, in the proposed fix original data is not modified (json coordinate files are still the same and can be imported in eman without any problems). The modified is output set of coordinates..  Otherwise user cannot even display e2boxer picking results - they will be wrong. He will be surprised why when picking everything was ok and when he has finished the results are all wrong. Maybe we can display warning as before (for tif files) but maybe add an option to "fix coordinates (default true)" to this warning?

**Comment by pconesa** [comment]
Hi @azazellochg, it seems that not always there is this flip. I haven't checked with different flavours of tif or DM3 and do not have time to be sure. It is related to [this](https://groups.google.com/forum/#!searchin/eman2/flip%7Csort:date/eman2/LGrSWsO7Xjk/BVgj1VEiLmsJ) but can't tell clearly if the flip will happen always or depending on the "dm3/tiff" flavour.

**Comment by azazellochg** [comment]
Hi @pconesa [here](https://groups.google.com/d/msg/eman2/2seQ_--IlLY/ujOCcxES4NgJ) is the bugfix they did on this. Ok then, let's keep a warning for now. In this case coordinate flip protocol needs to be added.

**Comment by pconesa** [comment]
At the end we agreed on having a parameter for eman boxer to file Y coordinates and war about it if format are tif or dm3. By default it will not flip Y which will be fine for mrc files.

**Comment by azazellochg** [comment]
fixed in df25b1f
