### ISSUE TITLE
RCT failure - Protocol failed: 'NoneType' object has no attribute 'getAngles'

### ISSUE THREAD

**Issue by kylelmorris** [I2PC/scipion#607]
I have picked particles using Kai Zhang's gautomatch, imported these and used the assignment tilt pair protocol. When I try to run RCT from the stable classes and against the extracted particles I get the following error.

Protocol failed: 'NoneType' object has no attribute 'getAngles'

Can you advise where I should look to check that the angles have been stored properly, or a way to fix this? The associated log files with this RCT protocol are attached.

Thanks for your help!

[002343_XmippProtRCT_logs.zip](https://github.com/I2PC/scipion/files/528542/002343_XmippProtRCT_logs.zip)

**Comment by cossorzano** [comment]
Dear Kylel,

this error sounds familiar to me, and I think it has been fixed in the 
devel branch. In any case, I'm forwarding your mail to the person in 
charge of that part of the code.

Kind regards, Carlos Oscar

**Comment by kylelmorris** [comment]
Thanks! Perhaps I switch and pull from that branch and it'll work out?

**Comment by cossorzano** [comment]
Try that, that is certainly an option.

Kind regards, Carlos Oscar

**Comment by kylelmorris** [comment]
On a different RCT project and have switched to the devel branch (devel (2016-12-14)) and reinstalled Scipion but still get the error relating to "Protocol failed: 'NoneType' object has no attribute 'getAngles'".

Has this been fixed for sure? Or can someone help me debug please?

Thanks a lot!

[logs.zip](https://github.com/I2PC/scipion/files/653489/logs.zip)

**Comment by pconesa** [comment]
Sorry to hear that, we are looking into this and will help you. Thanks for the logs zip file. I'm exploring them.

**Comment by Vilax** [comment]
Dear kylelmorris

we regret to hear that problem. 

In order to make it work, let me ask you some questions, that we cannot see with the log files.

1) please change the branch to devel and install as you did it before. 
2) Last time in devel, you got the same fail involving getAngles(). If I'm right the problem comes from extract particles instead of random conical tilt (due to the scipion internal structure). In extract particle we had modified the getAngles function, so that, please, relaunch the extract particles pairs and your workflow from that protocol. If it still fails, report us the again the problem, and we will considers new alternatives, because we will need more information about your workflow.

I would like to suggest you an advice. In your current workflow you use tilt pairs picking, and then applied the assignment tilt pairs. This last method is not necessary, due to in once you pick the tilt pairs manually, the tilt pairs of particles are assigned. The assignment of tilt pairs, make use of two individual pciking, one for the untilted micrograph, and other for the tilted micrograph. Then, the assignment of tilt pairs use both pickings and performs the tilt pair assignment avoiding the manual picking. 

I hope this information can help you, and the error will be fixed.

Regards

JL Vilas

**Comment by kylelmorris** [comment]
Hi JL Vilas,

Thanks for getting in touch.

I had already changed to the devel branch, reinstalled and on the same data set tried running the RCT again and got this error. Output from git branch below:

	$ git branch
	* devel
	  master

Prior to this I was on the master branch and had the same error.

I should clarify my workflow for a second, to avoid manual picking for now I have been picking externally with gautomatch on tilted and untitled, importing these coordinates via interactive tilt pair picking, then for the reasons you describe running tilt pair assignment.

Anyway, I have re-run from the assignment tiltpair stage when now using the devel branch, but then get the same error at the RCT stage:

	00026:   AttributeError: 'NoneType' object has no attribute 'getAngles'
	00027:   Protocol failed: 'NoneType' object has no attribute 'getAngles'
	00028:   FAILED: createRctImagesStep, step 1
	00029:     2016-12-16 10:12:05.686004
	00030:   ------------------- PROTOCOL FAILED (DONE 1/38)

So on the same data I went back to the micrographs and then manually picked from two tilt pairs totalling about ~150 ptcls. As a test, I have extracted the ~150 ptcls, extracted and 2D averaged. From this workflow from the same data, RCT runs fine. So it is likely something to do with the external picking and tilt pair assignment workflow I'm using. What do you think?

Thanks!
Kyle

**Comment by Vilax** [comment]
Dear Kyle,

Thanks for your reply. 

Gautomatch has been recently added to devel branch, so that, next time you can perform the picking with gautomatch inside scipion framework.

You workflow seems to be right, nevertheless, I do not recommend you to import the coordinates in the tilt pair picking. Instead of that I suggest the next one:

1) Three imports:
- Import the micrograph tilt pairs
- Import the Untilted coordinates
- Import the Tilted coordinates
You can do this, in the import tap in SPA.
2) Use the assignment tilt pairs using the coordinates and micrographs as input.
3) Extract particles, and continue with the workflow as you did it before.
![workflow_support](https://cloud.githubusercontent.com/assets/12271438/21317572/fea60466-c605-11e6-86aa-774516a1d38b.png)

If it is still failing, I would ask you the coordinates files from gautomacht, or a micrograph from your dataset. 

I hope, it will work

Regards

JL Vilas

**Comment by kylelmorris** [comment]
Hi Vilas,

Thanks for the information. I am running the workflow again from scratch but imported the coordinates as you suggested, hopefully all will be well with this. Thanks again and will let you know!

Best,
Kyle

**Comment by Vilax** [comment]
Hi Kyle,

Happy new year

Could you check the workflow again? We are interested in your issue

Regards

Vilas

**Comment by pconesa** [comment]
Hi @kylelmorris, is this fixed?

**Comment by kylelmorris** [comment]
Hi team,

Sorry for massive delay in replying. According to @Vilax suggestion earlier importing gautomatch co-ordinates separately worked in subsequent RCT reconstruction. I did get a cl2d error a the evaluate classes protocol but this didn't prevent the RCT from working. At the time I was using the devel branch.

Thank you for your help and suggestions!

![screenshot from 2017-01-24 12 28 35](https://cloud.githubusercontent.com/assets/19749872/22265384/b771ce62-e230-11e6-800c-92113a1b7988.png)

**Comment by pconesa** [comment]
Thanks Kyle!

We fixed a cl2d problem 
<https://github.com/I2PC/scipion/commit/6141d140588bfdf66d492ee6b810194d8f689ff6> 
recently (cl2d was looking for file in the first iteration and those 
files are not meant to be there).

If you this this is not the case, we would really appreciate more 
details in order to fix it. Otherwise, a git pull will bring the bugfix.

All the best, Pablo.
